### ISSUE TITLE
how quizzes work is puzzling

### ISSUE THREAD

**Issue by wpannell** [kentcdodds/modern-javascript#6]
The repository is setup like a ruby koan, for which you have to write code to pass the tests as a way of learning the technique or topic.

However, there is a `quiz.js`, for which I can find no instruction to follow.

There are many ways I can imagine to proceed, e.g., write a test to verify the answer to the question, write a comment sketching the answer, etc.

How do you propose we address the quizzes?

**Comment by kentcdodds** [comment]
The quiz is for me to run while I'm giving workshop as a live presentation. It's not intended for use without a live instructor.
